// src/App.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Block from './components/Block';
import Button from './components/Button';
import { faCat, faCode } from '@fortawesome/free-solid-svg-icons';
import data from './data';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import { LazyMotion, MotionConfig, domAnimation, m } from 'framer-motion';
import Ocho from './components/Ocho';

function App() {
  return (
    <MotionConfig reducedMotion='user'>
      <LazyMotion features={domAnimation}>
        <div className='flex flex-col xl:grid xl:grid-cols-12 xl:row-auto max-md:p-6 xl:h-full xl:place-content-center xl:my-auto xl:min-h-screen gap-y-8 xl:py-48'>
          <Block>
            {/* I'll get around simplifying this eventually */}
            <div className='flex flex-row justify-between items-center'>
              <div className='flex flex-col gap-y-1 font-extrabold text-[48px]'>
                <div className='flex flex-row gap-x-2 items-baseline'>
                  <span>Virkkunen</span>
                </div>
                <span className='text-overlay2 text-lg font-fira-condensed'>
                  "They said I could become anything, so I became a disappointment."
                </span>
              </div>
              <m.div
                whileHover={{
                  scale: 1.2,
                }}
              >
                <FontAwesomeIcon
                  className='transition-all ease-in-out duration-200 rounded-2xl hover:bg-clip-content hover:text-transparent hover:bg-gradient-to-b hover:from-[#FF218C] hover:via-[#FFD800] hover:to-[#21B1FF]'
                  icon={faCat}
                  color='#d20f39'
                  size='4x'
                />
              </m.div>
            </div>
            <span className='text-subtext1 text-lg max-sm:text-sm font-medium mt-6'>
              Hej, I'm Virkkunen! You can call me Vikki or V.{' '}
              <span className='text-subtext0 text-[0.9rem]'>
                vrkknn is Virkkunen without the vowels.
              </span>
            </span>
            <span className='text-subtext1 text-lg max-sm:text-sm font-medium mt-2'>
              I'm a web developer and film major currently based in Hungary. Also a tech enthusiast,
              FOSS supporter, hobbyist artist{' '}
              <span className='text-subtext0 text-[0.9rem]'>and I use arch btw</span>
            </span>
          </Block>

          <Block
            title='Some projects'
            buttonGroup
          >
            {data.portfolio.map((item) => (
              <Button
                title={item.title}
                icon={item.icon}
                color={item.color}
                link={item.link}
                key={item.title}
                tooltipTarget={item.title.replace(/\s/g, '')}
                tooltip={item.tooltip}
              />
            ))}
          </Block>

          <Block
            title='Services'
            buttonGroup
          >
            {data.services.map((item) => (
              <Button
                title={item.title}
                icon={item.icon}
                color={item.color}
                link={item.link}
                key={item.title}
                tooltipTarget={item.title.replace(/\s/g, '')}
                tooltip={item.tooltip}
              />
            ))}
          </Block>

          <Block
            title='Contact me'
            buttonGroup
          >
            {data.contact.map((item) => (
              <Button
                title={item.title}
                icon={item.icon}
                color={item.color}
                link={item.link}
                key={item.title}
                tooltipTarget={item.title.replace(/\s/g, '')}
                tooltip={item.tooltip}
              />
            ))}
          </Block>

          <Block
            title='88x31'
            retroGroup
          >
            {data.oitoOitoTresUm.map((item) => (
              <Ocho
                title={item.title}
                image={item.image}
                link={item.link}
                alt={item.alt ?? item.title}
                tooltipTarget={item.title}
                key={item.title}
              />
            ))}
          </Block>

          <Block>
            <div className='flex flex-row justify-around xl:mx-auto xl:gap-24'>
              <a
                className='flex flex-row items-center gap-x-1 transition-all ease-in-out duration-200 hover:text-blue active:text-lavender'
                target='_blank'
                rel='noreferrer noopener'
                href='https://github.com/Virkkunen'
              >
                <FontAwesomeIcon
                  icon={faGithub}
                  fixedWidth
                />
                <span>Virkkunen</span>
              </a>
              <span className='text-overlay2'>•</span>
              <a
                className='flex flex-row items-center gap-x-1 transition-all ease-in-out duration-200 hover:text-blue active:text-lavender'
                target='_blank'
                rel='noreferrer noopener'
                href='https://github.com/Virkkunen/virkkunen.github.io'
              >
                <FontAwesomeIcon
                  icon={faCode}
                  fixedWidth
                />
                <span>source</span>
              </a>
            </div>
          </Block>
        </div>
      </LazyMotion>
    </MotionConfig>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import Block from './components/Block.vue';
import LinkButton from './components/LinkButton.vue';
import Footer from './components/Footer.vue';
import { siteData } from './data/content';
import Badge from './components/Badge.vue';
</script>

<template>
  <main
    class="bg-ctp-crust fira-sans-semibold min-h-screen w-full text-ctp-text flex flex-col xl:grid xl:grid-cols-12 xl:row-auto p-8 lg:p-24 xl:p-0 xl:place-content-center-safe xl:my-auto gap-y-8 xl:py-48"
  >
    <Block>
      <div class="grid grid-cols-3 grid-rows-2 items-center mb-4 xl:mb-2">
        <h1 class="text-4xl xl:text-5xl fira-sans-bold">Virkkunen</h1>
        <font-awesome-icon
          icon="fa-solid fa-cat"
          widthAuto
          class="text-4xl xl:text-6xl text-ctp-red col-start-3 justify-self-end xl:row-span-2"
        />
        <span
          class="fira-sans-condensed-semibold text-ctp-subtext0 text-sm col-span-3 xl:col-span-2"
        >
          "They said I could become anything, so I became a disappointment."
        </span>
      </div>
      <div class="flex flex-col gap-y-2 max-md:text-[1.1rem]">
        <span>
          Hej, I'm Virkkunen! You can call me Vikki or V.
          <small class="fira-sans-condensed-semibold text-ctp-subtext0"
            >vrkknn is Virkkunen without the vowels.</small
          >
        </span>
        <span>
          I'm a web developer and film major currently based in Hungary. Also a tech enthusiast,
          FOSS supporter, hobbyist artist
          <small class="fira-sans-condensed-semibold text-ctp-subtext0">and I use arch btw</small>
        </span>
      </div>
    </Block>
    <Block
      title="Some projects"
      buttonGroup
    >
      <LinkButton
        v-for="project in siteData.projects"
        :title="project.title"
        :icon="project.icon"
        :colour="project.colour"
        :link="project.link"
        :tooltip="project.tooltip"
      />
    </Block>
    <Block
      title="Services"
      buttonGroup
    >
      <LinkButton
        v-for="service in siteData.services"
        :title="service.title"
        :icon="service.icon"
        :colour="service.colour"
        :link="service.link"
        :tooltip="service.tooltip"
      />
    </Block>
    <Block
      title="Contact me"
      buttonGroup
    >
      <LinkButton
        v-for="contact in siteData.contact"
        :title="contact.title"
        :icon="contact.icon"
        :colour="contact.colour"
        :link="contact.link"
        :tooltip="contact.tooltip"
      />
    </Block>
    <Block
      title="88x31"
      badgeGroup
    >
      <Badge
        v-for="badge in siteData.badges"
        :title="badge.title"
        :image="badge.image"
        :link="badge.link"
        :alt="badge.alt"
        :tooltip="badge.title"
      />
    </Block>
    <Footer />
  </main>
</template>

<style scoped>
body {
  background-color: var(--color-ctp-crust);
}
</style>
